### ISSUE TITLE
Criar uma classe Gato

### ISSUE THREAD

**Issue by narukaioh** [narukaioh/estudando-git#1]
Deve ser criada uma classe Gato que deve ter os seguintes metodos:

- falar()

- comer( alimento )
Deve ser enviado por parametro um alimento, e no metodo deve informar
**nome-do-animal** está comendo **alimento**

Depois adicionar um gato na função **main** e informar um alimento para o novo metodo

**Comment by lilih9** [comment]
Efetuado criação de classe gato.
